import Header from "@/components/ui/header";
import "../../styles/global.css";
export const metadata = {
  title: "Auth",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <Header />
      {children}
    </main>
  );
}
